project:
  type: website
  output-dir: docs

website:
  title: "Tate Jacobson"
  open-graph: true
  navbar:
    logo: logo.png
    title: false
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd

format:
  html:
    grid:
      body-width: 1400px
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: custom.css
