---
title: "Research"
---

### Refereed Publications 

- **Jacobson, T.** and Zou, H. (accepted), “Linear Hypothesis Testing for High Dimensional Tobit Models,” *Statistica Sinica*, DOI: [10.5705/ss.202023.0118](https://doi.org/10.5705/ss.202023.0118)
- **Jacobson, T.** and Zou, H. (2023), “High-Dimensional Censored Regression via the Penalized Tobit Likelihood,” *Journal of Business and Economic Statistics*, DOI: [10.1080/07350015.2023.2182309](https://doi.org/10.1080/07350015.2023.2182309)
- Anderson, L. and **Jacobson, T.** (2023), “Providing the choice of in-person or video-conference attendance in a Clinical Physiology course may harm learning outcomes for the entire cohort,” *Advances in Physiology Education*, DOI: [10.1152/advan.00160.2022](https://doi.org/10.1152/advan.00160.2022)
- **Jacobson, T.** & Zou, H. (2021), “Do Predictor Envelopes Really Reduce Dimension?” *Journal of Data Science*, 4, 528-541. DOI: [10.6339/21-JDS1017](https://doi.org/10.6339/21-JDS1017)


### Preprints

- **Jacobson, T.**, “Strong Oracle Guarantees for Partial Penalized Tests of High Dimensional Generalized Linear Models,” arXiv: [2408.00270](https://arxiv.org/abs/2408.00270)


### Software  

- Jacobson T. (2022). tobitnet: Penalized Tobit Regression. R package version 1.0.0, [https://github.com/TateJacobson/tobitnet](https://github.com/TateJacobson/tobitnet)
- Jacobson T. (2023). TobitTest: Linear Hypothesis Testing for High Dimensional Tobit Models. R package version 1.0, [https://github.com/TateJacobson/TobitTest](https://github.com/TateJacobson/TobitTest)
